### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MSadeghzadehG**

### CODE REVIEW

**Review by 1995parham — COMMENTED** [review]
I agree with this new naming schema, but I think so here we must add the course table of our university so the contributors can use it.

**Comment by 1995parham** [comment]
@MSadeghzadehG @AliNazariii  Is there any source for this information? If there is one, please share it here.

**Comment by AliNazariii** [comment]
> @MSadeghzadehG @AliNazariii Is there any source for this information? If there is one, please share it here.

yes, our courses have course-num in our new educational plan.
ex. Discrete Mathematics is CE103.
I think we should provide a table for these in this repo. I will do it.

**Comment by 1995parham** [comment]
@AliNazariii ❤️ This would be awesome

**Comment by Bahador-Bakhshi** [comment]
This is the course codes: https://github.com/aut-ce/contribution/blob/master/course%20codes.docx

**Comment by AliNazariii** [comment]
> This is the course codes: https://github.com/aut-ce/contribution/blob/master/course%20codes.docx

Thanks :)

**Pull request merged**
